name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Linting repository"
      - run: echo "Running unit tests"

  build-and-push-ecr-image:
    name: Build & Push Docker
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y jq unzip
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  continuous-deployment:
    needs: build-and-push-ecr-image
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      # Configure AWS credentials
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Log in to ECR
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Pull the latest image from ECR
      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.AWS_ECR_LOGIN_URI }}:latest

      # Stop and remove old container if running
      - name: Stop old container
        env:
          CONTAINER_NAME: ${{ secrets.DOCKER_CONTAINER_NAME }}
        run: |
          if docker ps -q --filter "name=$CONTAINER_NAME" | grep -q .; then
            docker stop $CONTAINER_NAME
            docker rm -fv $CONTAINER_NAME
          fi

      # Run new container
      - name: Run Docker container
        env:
          CONTAINER_NAME: ${{ secrets.DOCKER_CONTAINER_NAME }}
        run: |
          docker run -d -p 80:8080 --name "$CONTAINER_NAME" \
            -e "MONGO_DB_URL=${{ secrets.MONGO_DB_URL }}" \
            -e "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -e "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -e "AWS_REGION=${{ secrets.AWS_REGION }}" \
            ${{ secrets.AWS_ECR_LOGIN_URI }}:latest

      # Clean old Docker resources
      - name: Clean Docker
        run: docker system prune -f

